-- Sekwencje oraz tabele przechowujace obiekty


CREATE SEQUENCE MIEJSCA_TAB_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE MIEJSCA_TAB OF MIEJSCE_TYP (
    PRIMARY KEY (MIEJSCE_ID)
);

CREATE SEQUENCE seq_dyscyplina_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_wystep_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_zawodnik_id START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE Osoba_tab OF Osoba_typ (
    CONSTRAINT CK_Active CHECK (Active IN (0, 1))
)
NESTED TABLE Wystepy STORE AS Wystepy_Table
NESTED TABLE Dyscypliny STORE AS Dyscyplina_Table
NESTED TABLE Wyniki_dyscyplin STORE AS PB_Wynik_Table;

CREATE SEQUENCE AKTYWNOSCI_TAB_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE AKTYWNOSCI_TAB OF AKTYWNOSCI_TYP (
    PRIMARY KEY (AKTYWNOSC_ID)
)
NESTED TABLE Lista_osob STORE AS Lista_osob_s;

CREATE SEQUENCE RAPORT_TAB_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE RAPORTY_TAB OF RAPORT_OBECNOSCI (
    PRIMARY KEY (RAPORT_ID)
)
NESTED TABLE LISTA_ZAPISANYCH STORE AS LISTA_ZAP
NESTED TABLE LISTA_OBECNYCH STORE AS LISTA_OB;
/